name: labcalc2
description: "Laboratory Scientific Calculator"
publish_to: 'none'
version: 1.0.10+28

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_color: ^2.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_secure_storage: ^9.0.0
  mailto: ^2.0.0
  url_launcher: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/labCalc.png"
  min_sdk_android: 24

flutter:
  uses-material-design: true
  assets:
    - assets/images/absolute_deviation.png
    - assets/images/arithmetic.png
    - assets/images/hamonic.png
    - assets/images/rms.png
    - assets/images/squared_error.png
    - assets/icons/labCalc.png
    - assets/images/buttons/

  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Thin.ttf
          weight: 100
        - asset: assets/fonts/RobotoMono-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/RobotoMono-Light.ttf
          weight: 300
        - asset: assets/fonts/RobotoMono-Regular.ttf
          weight: 400
        - asset: assets/fonts/RobotoMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/RobotoMono-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/RobotoMono-Bold.ttf
          weight: 700
      
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 900

    - family: HedvigLettersSerif
      fonts:
        - asset: assets/fonts/HedvigLettersSerif-Regular.ttf
          weight: 400

